"""Explicit finite grammar/trace construction for CREST temporal interaction.

Unlike ``compositional_temporal_game``, this module does not assign coalition
bit values directly.  Each responsibility contributes primitive interface
symbols.  Legal query words are generated compositionally from the symbols
available to a coalition, traces are evaluated on an explicit finite carrier,
and the exact state is the quotient induced by equality of all legal traces.

The exterior decoder is a *typed composition*: it consumes both a history
handle and a mechanism handle before an F decoder may read an exterior bit.
Consequently the decoder word does not exist in any proper coalition grammar.
This is a structural property of the grammar generator, not a coalition-value
lookup table.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from math import log2
from typing import Iterable

HISTORY = "H"
MECHANISM = "THETA"
FUTURE = "F"
AXES = (HISTORY, MECHANISM, FUTURE)


@dataclass(frozen=True)
class World:
    history: int
    mechanism: int
    exterior: tuple[int, ...]


@dataclass(frozen=True)
class Word:
    """A well-typed observable word generated from responsibility primitives."""

    kind: str
    index: int | None = None


def worlds(bit_depth: int) -> tuple[World, ...]:
    if not isinstance(bit_depth, int) or isinstance(bit_depth, bool) or bit_depth < 1:
        raise ValueError("bit_depth must be a positive integer")
    return tuple(
        World(h, theta, exterior)
        for h, theta in product((0, 1), repeat=2)
        for exterior in product((0, 1), repeat=bit_depth)
    )


def normalize_coalition(coalition: Iterable[str]) -> frozenset[str]:
    members = frozenset(coalition)
    if not members.issubset(AXES):
        raise ValueError("coalition contains an unknown responsibility")
    return members


def legal_words(bit_depth: int, coalition: Iterable[str]) -> tuple[Word, ...]:
    """Generate the legal observable grammar from primitive responsibilities.

    H contributes a history-handle observation and THETA contributes a mechanism-
    handle observation. F contributes decoder primitives, but a decoder is
    well-typed only after *both* interface handles are available. Thus an exterior
    read is generated by compositional typing rather than by directly checking a
    preassigned coalition value.
    """

    if not isinstance(bit_depth, int) or isinstance(bit_depth, bool) or bit_depth < 1:
        raise ValueError("bit_depth must be a positive integer")
    members = normalize_coalition(coalition)
    words: list[Word] = []
    has_h_handle = HISTORY in members
    has_theta_handle = MECHANISM in members
    has_decoder_primitive = FUTURE in members

    if has_h_handle:
        words.append(Word("history"))
    if has_theta_handle:
        words.append(Word("mechanism"))

    # Typed composition rule: decode_i : HHandle x ThetaHandle x FDecoder -> Bit.
    if has_h_handle and has_theta_handle and has_decoder_primitive:
        words.extend(Word("exterior", i) for i in range(bit_depth))
    return tuple(words)


def trace(world: World, word: Word) -> int:
    if word.kind == "history":
        return world.history
    if word.kind == "mechanism":
        return world.mechanism
    if word.kind == "exterior":
        if word.index is None or not 0 <= word.index < len(world.exterior):
            raise ValueError("invalid exterior decoder index")
        return world.exterior[word.index]
    raise ValueError(f"unknown word kind: {word.kind}")


def trace_profile(world: World, grammar: tuple[Word, ...]) -> tuple[int, ...]:
    return tuple(trace(world, word) for word in grammar)


def induced_classes(bit_depth: int, coalition: Iterable[str]) -> tuple[tuple[World, ...], ...]:
    """Return exact trace-equivalence classes under the generated grammar."""

    grammar = legal_words(bit_depth, coalition)
    buckets: dict[tuple[int, ...], list[World]] = {}
    for world in worlds(bit_depth):
        buckets.setdefault(trace_profile(world, grammar), []).append(world)
    return tuple(tuple(bucket) for bucket in buckets.values())


def quotient_size(bit_depth: int, coalition: Iterable[str]) -> int:
    return len(induced_classes(bit_depth, coalition))


def quotient_bits(bit_depth: int, coalition: Iterable[str]) -> float:
    return log2(quotient_size(bit_depth, coalition))


def coalition_table(bit_depth: int) -> dict[frozenset[str], float]:
    table: dict[frozenset[str], float] = {}
    for mask in range(1 << len(AXES)):
        coalition = frozenset(AXES[i] for i in range(len(AXES)) if mask & (1 << i))
        table[coalition] = quotient_bits(bit_depth, coalition)
    return table


def mobius_three_way(bit_depth: int) -> float:
    v = coalition_table(bit_depth)
    h = frozenset((HISTORY,))
    theta = frozenset((MECHANISM,))
    future = frozenset((FUTURE,))
    htheta = h | theta
    hf = h | future
    thetaf = theta | future
    grand = frozenset(AXES)
    empty = frozenset()
    return (
        v[grand]
        - v[htheta]
        - v[hf]
        - v[thetaf]
        + v[h]
        + v[theta]
        + v[future]
        - v[empty]
    )


def exclusive_joint_addressability(bit_depth: int) -> bool:
    """Whether exterior information is invisible to every proper coalition.

    This is checked from generated grammars and traces, not stipulated in a value
    function. The grand coalition must distinguish all exterior signatures while
    every proper coalition must be invariant to changing exterior bits at fixed
    history/mechanism values.
    """

    grand = frozenset(AXES)
    grand_grammar = legal_words(bit_depth, grand)
    if not any(word.kind == "exterior" for word in grand_grammar):
        return False

    for mask in range(1 << len(AXES)):
        coalition = frozenset(AXES[i] for i in range(len(AXES)) if mask & (1 << i))
        grammar = legal_words(bit_depth, coalition)
        if coalition != grand and any(word.kind == "exterior" for word in grammar):
            return False
    return True


__all__ = [
    "AXES",
    "FUTURE",
    "HISTORY",
    "MECHANISM",
    "World",
    "Word",
    "coalition_table",
    "exclusive_joint_addressability",
    "induced_classes",
    "legal_words",
    "mobius_three_way",
    "quotient_bits",
    "quotient_size",
    "trace",
    "trace_profile",
    "worlds",
]
