"""Exact numeric obstruction spectra for small CREST audit sets.

For a declared finite common carrier, let v(S) be the state debt of the least
common fixed point generated by audit coalition S relative to one baseline.
This module reports:

- standalone debt D_i = v({i});
- joint debt v(N);
- non-additive excess Delta = v(N) - sum_i D_i;
- exact Shapley attribution phi_i of the joint debt across audits;
- interaction attribution phi_i - D_i, which sums to Delta; and
- exact coalition interaction dividends from the Möbius transform of v.

The Shapley and Möbius calculations are standard cooperative-game accounting.
CREST uses them only as order-independent diagnostics of how much joint state
resolution is assigned to individual scientific responsibilities and to their
interactions. Exact enumeration is exponential in the number of audits and is
intended for the small audit sets used by CREST contracts.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from math import factorial
from typing import Hashable, Iterable

from .joint_debt import joint_partition, state_bits
from .joint_state import AuditRefinement

PartitionLike = Iterable[Hashable]


def _block_count(partition: PartitionLike) -> int:
    labels: dict[Hashable, int] = {}
    count = 0
    for value in partition:
        try:
            hash(value)
        except TypeError as error:
            raise ValueError("partition labels must be hashable") from error
        if value not in labels:
            labels[value] = count
            count += 1
    if count == 0:
        raise ValueError("partition must be nonempty")
    return count


@dataclass(frozen=True)
class CoalitionDebt:
    """State debt and block count for one audit coalition."""

    audits: tuple[str, ...]
    debt: float
    blocks: int


@dataclass(frozen=True)
class InteractionDividend:
    """Exact Möbius interaction term for one nonempty audit coalition."""

    audits: tuple[str, ...]
    bits: float

    @property
    def order(self) -> int:
        return len(self.audits)


@dataclass(frozen=True)
class ObstructionSpectrumReport:
    """Standalone, joint, and order-independent audit contributions."""

    audit_names: tuple[str, ...]
    standalone_debts: tuple[float, ...]
    shapley_contributions: tuple[float, ...]
    interaction_attributions: tuple[float, ...]
    shapley_shares: tuple[float, ...]
    joint_debt: float
    delta: float
    baseline_blocks: int
    joint_blocks: int
    coalition_debts: tuple[CoalitionDebt, ...]
    interaction_dividends: tuple[InteractionDividend, ...]

    def verify(self, *, tolerance: float = 1e-12) -> bool:
        size = len(self.audit_names)
        singleton_dividends = {
            dividend.audits[0]: dividend.bits
            for dividend in self.interaction_dividends
            if dividend.order == 1
        }
        return (
            size >= 1
            and len(set(self.audit_names)) == size
            and len(self.standalone_debts) == size
            and len(self.shapley_contributions) == size
            and len(self.interaction_attributions) == size
            and len(self.shapley_shares) == size
            and self.baseline_blocks >= 1
            and self.joint_blocks >= self.baseline_blocks
            and all(value >= -tolerance for value in self.standalone_debts)
            and all(value >= -tolerance for value in self.shapley_contributions)
            and self.joint_debt >= -tolerance
            and abs(self.delta - (self.joint_debt - sum(self.standalone_debts)))
            <= tolerance
            and abs(sum(self.shapley_contributions) - self.joint_debt) <= tolerance
            and all(
                abs(interaction - (shapley - standalone)) <= tolerance
                for interaction, shapley, standalone in zip(
                    self.interaction_attributions,
                    self.shapley_contributions,
                    self.standalone_debts,
                )
            )
            and abs(sum(self.interaction_attributions) - self.delta) <= tolerance
            and abs(sum(item.bits for item in self.interaction_dividends) - self.joint_debt)
            <= tolerance
            and all(
                abs(singleton_dividends[name] - standalone) <= tolerance
                for name, standalone in zip(self.audit_names, self.standalone_debts)
            )
            and abs(
                sum(item.bits for item in self.interaction_dividends if item.order >= 2)
                - self.delta
            )
            <= tolerance
            and (
                abs(sum(self.shapley_shares) - 1.0) <= tolerance
                if self.joint_debt > tolerance
                else all(abs(value) <= tolerance for value in self.shapley_shares)
            )
        )


def obstruction_spectrum(
    audits: Iterable[AuditRefinement], baseline: PartitionLike
) -> ObstructionSpectrumReport:
    """Compute the exact coalition table and obstruction spectrum.

    The characteristic value v(S) is the state debt of the least common fixed
    point of coalition S relative to ``baseline``. The empty coalition has zero
    debt and leaves the baseline unchanged. Shapley values allocate total joint
    debt across named audits; Möbius dividends decompose the same joint debt into
    exact singleton, pairwise, triple, and higher-order coalition terms.
    """

    audit_tuple = tuple(audits)
    if not audit_tuple:
        raise ValueError("at least one audit is required")
    names = tuple(audit.name for audit in audit_tuple)
    if len(set(names)) != len(names):
        raise ValueError("audit names must be unique")
    baseline_tuple = tuple(baseline)
    baseline_blocks = _block_count(baseline_tuple)
    if any(audit.world_count != len(baseline_tuple) for audit in audit_tuple):
        raise ValueError("all audits and baseline must share one finite carrier")

    coalition_values: dict[frozenset[int], tuple[float, int]] = {
        frozenset(): (0.0, baseline_blocks)
    }
    coalition_rows: list[CoalitionDebt] = [
        CoalitionDebt(audits=(), debt=0.0, blocks=baseline_blocks)
    ]

    for size in range(1, len(audit_tuple) + 1):
        for indices in combinations(range(len(audit_tuple)), size):
            coalition = frozenset(indices)
            selected = tuple(audit_tuple[index] for index in indices)
            partition = joint_partition(selected, baseline_tuple)
            debt = state_bits(partition) - state_bits(baseline_tuple)
            blocks = _block_count(partition)
            coalition_values[coalition] = (debt, blocks)
            coalition_rows.append(
                CoalitionDebt(
                    audits=tuple(names[index] for index in indices),
                    debt=debt,
                    blocks=blocks,
                )
            )

    full = frozenset(range(len(audit_tuple)))
    joint_debt = coalition_values[full][0]
    joint_blocks = coalition_values[full][1]
    standalone = tuple(
        coalition_values[frozenset((index,))][0]
        for index in range(len(audit_tuple))
    )

    total_factorial = factorial(len(audit_tuple))
    shapley: list[float] = []
    for index in range(len(audit_tuple)):
        others = tuple(
            other for other in range(len(audit_tuple)) if other != index
        )
        contribution = 0.0
        for size in range(len(others) + 1):
            weight = (
                factorial(size)
                * factorial(len(audit_tuple) - size - 1)
                / total_factorial
            )
            for subset_tuple in combinations(others, size):
                subset = frozenset(subset_tuple)
                with_index = subset | frozenset((index,))
                contribution += weight * (
                    coalition_values[with_index][0] - coalition_values[subset][0]
                )
        shapley.append(contribution)

    dividends: list[InteractionDividend] = []
    for size in range(1, len(audit_tuple) + 1):
        for indices in combinations(range(len(audit_tuple)), size):
            coalition = frozenset(indices)
            bits = 0.0
            index_tuple = tuple(indices)
            for subset_size in range(size + 1):
                for subset_tuple in combinations(index_tuple, subset_size):
                    subset = frozenset(subset_tuple)
                    sign = -1.0 if (size - subset_size) % 2 else 1.0
                    bits += sign * coalition_values[subset][0]
            dividends.append(
                InteractionDividend(
                    audits=tuple(names[index] for index in indices),
                    bits=bits,
                )
            )

    shapley_tuple = tuple(shapley)
    interaction = tuple(
        shapley_value - standalone_value
        for shapley_value, standalone_value in zip(shapley_tuple, standalone)
    )
    shares = (
        tuple(value / joint_debt for value in shapley_tuple)
        if joint_debt > 1e-12
        else tuple(0.0 for _ in shapley_tuple)
    )
    delta = joint_debt - sum(standalone)

    report = ObstructionSpectrumReport(
        audit_names=names,
        standalone_debts=standalone,
        shapley_contributions=shapley_tuple,
        interaction_attributions=interaction,
        shapley_shares=shares,
        joint_debt=joint_debt,
        delta=delta,
        baseline_blocks=baseline_blocks,
        joint_blocks=joint_blocks,
        coalition_debts=tuple(coalition_rows),
        interaction_dividends=tuple(dividends),
    )
    if not report.verify():
        raise AssertionError("constructed obstruction-spectrum report did not verify")
    return report


def three_obstruction_cascade(
) -> tuple[
    tuple[int, ...],
    tuple[AuditRefinement, AuditRefinement, AuditRefinement],
]:
    """Six-world CCOC -> MLTR -> MRM cascade with numeric interaction debt.

    Worlds are ordered ``z, a, b, c, r, s``. The baseline distinguishes ``z``
    from all live worlds. CCOC can first distinguish ``a`` because its future
    successor reaches ``z``. That split lets the MLTR audit distinguish ``b``
    through ``b -> a``. The MLTR split then lets MRM distinguish ``c`` through
    ``c -> b``. Acting alone from the baseline, MLTR and MRM cost zero.
    """

    world_count = 6
    baseline = (0, 1, 1, 1, 1, 1)
    static = ("same",) * world_count

    def successor_rows(special: dict[int, int]) -> tuple[tuple[int, ...], ...]:
        successor = [4] * world_count
        successor[0] = 0
        successor[4] = 4
        successor[5] = 4
        for source, target in special.items():
            successor[source] = target
        return tuple((target,) for target in successor)

    ccoc = AuditRefinement(
        "CCOC",
        static,
        ("future",),
        successor_rows({1: 0}),
    )
    mltr = AuditRefinement(
        "MLTR",
        static,
        ("inheritance",),
        successor_rows({2: 1}),
    )
    mrm = AuditRefinement(
        "MRM",
        static,
        ("mechanism",),
        successor_rows({3: 2}),
    )
    return baseline, (ccoc, mltr, mrm)


def three_obstruction_spectrum() -> ObstructionSpectrumReport:
    """Return the canonical six-world CCOC/MLTR/MRM spectrum witness."""

    baseline, audits = three_obstruction_cascade()
    return obstruction_spectrum(audits, baseline)


__all__ = [
    "CoalitionDebt",
    "InteractionDividend",
    "ObstructionSpectrumReport",
    "obstruction_spectrum",
    "three_obstruction_cascade",
    "three_obstruction_spectrum",
]
