"""Quantitative CREST obstruction spectrum on a finite common carrier.

For structural audits indexed by N, define coalition debt

    v(S) = log2 |J_S| - log2 |B|,

where J_S is the least common fixed point of the audits in coalition S above the
baseline partition B. The Shapley obstruction contribution of audit i is the
average marginal debt it adds over all insertion orders. This gives an
order-independent additive attribution of joint state debt while retaining
CREST's non-additive interaction diagnostic Delta.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from math import factorial
from typing import Hashable, Iterable

from .joint_debt import _canonical, joint_partition, state_bits
from .joint_state import AuditRefinement

PartitionLike = Iterable[Hashable]


def _coalitions(size: int) -> Iterable[tuple[int, ...]]:
    for coalition_size in range(size + 1):
        yield from combinations(range(size), coalition_size)


def coalition_debt(
    audits: Iterable[AuditRefinement],
    baseline: PartitionLike,
    coalition: Iterable[int],
) -> float:
    """State debt generated by one subset of audits; empty coalition costs zero."""

    audit_tuple = tuple(audits)
    base = _canonical(baseline)
    if not audit_tuple:
        raise ValueError("at least one audit is required")
    if any(audit.world_count != len(base) for audit in audit_tuple):
        raise ValueError("all audits and baseline must share one finite carrier")
    indices = tuple(coalition)
    if len(set(indices)) != len(indices):
        raise ValueError("coalition indices must be unique")
    if any(
        not isinstance(index, int)
        or isinstance(index, bool)
        or index < 0
        or index >= len(audit_tuple)
        for index in indices
    ):
        raise ValueError("coalition indices must refer to supplied audits")
    if not indices:
        return 0.0
    selected = tuple(audit_tuple[index] for index in indices)
    joint = joint_partition(selected, base)
    return state_bits(joint) - state_bits(base)


@dataclass(frozen=True)
class ObstructionSpectrumReport:
    """Order-independent quantitative attribution of structural CREST debt."""

    audit_names: tuple[str, ...]
    standalone_debts: tuple[float, ...]
    shapley_contributions: tuple[float, ...]
    interaction_allocations: tuple[float, ...]
    joint_debt: float
    delta: float
    coalition_debts: tuple[tuple[tuple[str, ...], float], ...]
    baseline_blocks: int
    joint_blocks: int

    def verify(self, *, tolerance: float = 1e-12) -> bool:
        if len(set(self.audit_names)) != len(self.audit_names):
            return False
        if not (
            len(self.audit_names)
            == len(self.standalone_debts)
            == len(self.shapley_contributions)
            == len(self.interaction_allocations)
        ):
            return False
        return (
            self.baseline_blocks >= 1
            and self.joint_blocks >= self.baseline_blocks
            and all(value >= -tolerance for value in self.standalone_debts)
            and self.joint_debt >= -tolerance
            and abs(sum(self.shapley_contributions) - self.joint_debt) <= tolerance
            and all(
                abs(interaction - (shapley - standalone)) <= tolerance
                for interaction, shapley, standalone in zip(
                    self.interaction_allocations,
                    self.shapley_contributions,
                    self.standalone_debts,
                )
            )
            and abs(sum(self.interaction_allocations) - self.delta) <= tolerance
            and abs(self.delta - (self.joint_debt - sum(self.standalone_debts)))
            <= tolerance
        )


def obstruction_spectrum(
    audits: Iterable[AuditRefinement], baseline: PartitionLike
) -> ObstructionSpectrumReport:
    """Compute coalition debt, Shapley contributions, and interaction allocation."""

    audit_tuple = tuple(audits)
    base = _canonical(baseline)
    if not audit_tuple:
        raise ValueError("at least one audit is required")
    if any(audit.world_count != len(base) for audit in audit_tuple):
        raise ValueError("all audits and baseline must share one finite carrier")
    names = tuple(audit.name for audit in audit_tuple)
    if len(set(names)) != len(names):
        raise ValueError("audit names must be unique")

    n = len(audit_tuple)
    debt_by_indices = {
        coalition: coalition_debt(audit_tuple, base, coalition)
        for coalition in _coalitions(n)
    }
    standalone = tuple(debt_by_indices[(index,)] for index in range(n))
    full = tuple(range(n))
    joint = debt_by_indices[full]

    shapley: list[float] = []
    denominator = factorial(n)
    for index in range(n):
        others = tuple(other for other in range(n) if other != index)
        contribution = 0.0
        for coalition_size in range(n):
            weight = (
                factorial(coalition_size)
                * factorial(n - coalition_size - 1)
                / denominator
            )
            for coalition in combinations(others, coalition_size):
                before = tuple(sorted(coalition))
                after = tuple(sorted((*coalition, index)))
                contribution += weight * (
                    debt_by_indices[after] - debt_by_indices[before]
                )
        shapley.append(contribution)

    shapley_tuple = tuple(shapley)
    interaction = tuple(
        shapley_value - standalone_value
        for shapley_value, standalone_value in zip(shapley_tuple, standalone)
    )
    delta = joint - sum(standalone)
    joint_labels = joint_partition(audit_tuple, base)
    coalition_rows = tuple(
        (tuple(names[index] for index in coalition), debt_by_indices[coalition])
        for coalition in _coalitions(n)
    )
    result = ObstructionSpectrumReport(
        audit_names=names,
        standalone_debts=standalone,
        shapley_contributions=shapley_tuple,
        interaction_allocations=interaction,
        joint_debt=joint,
        delta=delta,
        coalition_debts=coalition_rows,
        baseline_blocks=max(base) + 1,
        joint_blocks=max(joint_labels) + 1,
    )
    if not result.verify():
        raise AssertionError("constructed obstruction-spectrum report did not verify")
    return result


__all__ = ["ObstructionSpectrumReport", "coalition_debt", "obstruction_spectrum"]
